-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2026-03-21 21:29:55 GMT
--   site:      SQL Server 2008
--   type:      SQL Server 2008



CREATE TABLE Dim_Customer 
    (
     SK_Customer NUMERIC (10) NOT NULL , 
     CustomerID VARCHAR (5) NOT NULL , 
     CustomerName VARCHAR (40) NOT NULL , 
     CustomerAge NUMERIC (28) , 
     AgeGroup VARCHAR (20) 
    )
GO

ALTER TABLE Dim_Customer ADD CONSTRAINT Dim_Customer_PK PRIMARY KEY CLUSTERED (SK_Customer)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Date 
    (
     SK_Date NUMERIC (10) NOT NULL , 
     FullDate DATE NOT NULL , 
     Day NUMERIC (28) , 
     Month NUMERIC (28) , 
     Quarter NUMERIC (28) , 
     Semester NUMERIC (28) , 
     Year NUMERIC (28) , 
     MonthName VARCHAR (20) , 
     IsWeekend CHAR (1) 
    )
GO

ALTER TABLE Dim_Date ADD CONSTRAINT Dim_Date_PK PRIMARY KEY CLUSTERED (SK_Date)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Location 
    (
     SK_Location NUMERIC (10) NOT NULL , 
     City VARCHAR (15) NOT NULL , 
     District VARCHAR (15) NOT NULL , 
     Country VARCHAR (255) NOT NULL , 
     Continent VARCHAR (255) NOT NULL 
    )
GO

ALTER TABLE Dim_Location ADD CONSTRAINT Dim_Location_PK PRIMARY KEY CLUSTERED (SK_Location)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Movie 
    (
     SK_Movie NUMERIC (10) NOT NULL , 
     MovieID NUMERIC (28) NOT NULL , 
     MovieName VARCHAR (255) NOT NULL , 
     MovieDuration VARCHAR (255) , 
     MovieBudget NUMERIC (28) , 
     GenreName VARCHAR (255) , 
     AgeRate VARCHAR (255) , 
     Language VARCHAR (100) , 
     Writer VARCHAR (255) , 
     ProducerName VARCHAR (255) , 
     ReleaseYear NUMERIC (28) 
    )
GO

ALTER TABLE Dim_Movie ADD CONSTRAINT Dim_Movie_PK PRIMARY KEY CLUSTERED (SK_Movie)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Platform 
    (
     SK_Platform NUMERIC (10) NOT NULL , 
     PlatformID NUMERIC (28) NOT NULL , 
     PlatformName VARCHAR (255) NOT NULL 
    )
GO

ALTER TABLE Dim_Platform ADD CONSTRAINT Dim_Platform_PK PRIMARY KEY CLUSTERED (SK_Platform)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Fact_Sales 
    (
     SK_Date NUMERIC (10) NOT NULL , 
     SK_Customer NUMERIC (10) NOT NULL , 
     SK_Movie NUMERIC (10) NOT NULL , 
     SK_Platform NUMERIC (10) NOT NULL , 
     SK_Location NUMERIC (10) NOT NULL , 
     Price NUMERIC (28) NOT NULL , 
     Discount NUMERIC (28) , 
     SaleAmount NUMERIC (28) , 
     Profit NUMERIC (28) , 
     Dim_Date_SK_Date NUMERIC (10) NOT NULL , 
     Dim_Customer_SK_Customer NUMERIC (10) NOT NULL , 
     Dim_Movie_SK_Movie NUMERIC (10) NOT NULL , 
     Dim_Platform_SK_Platform NUMERIC (10) NOT NULL , 
     Dim_Location_SK_Location NUMERIC (10) NOT NULL , 
     SaleID NUMERIC (10) NOT NULL , 
     Quantity NUMERIC (28) 
    )
GO

ALTER TABLE Fact_Sales ADD CONSTRAINT Fact_Sales_PK PRIMARY KEY CLUSTERED (SaleID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Customer_FK FOREIGN KEY 
    ( 
     Dim_Customer_SK_Customer
    ) 
    REFERENCES Dim_Customer 
    ( 
     SK_Customer 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Date_FK FOREIGN KEY 
    ( 
     Dim_Date_SK_Date
    ) 
    REFERENCES Dim_Date 
    ( 
     SK_Date 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Location_FK FOREIGN KEY 
    ( 
     Dim_Location_SK_Location
    ) 
    REFERENCES Dim_Location 
    ( 
     SK_Location 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Movie_FK FOREIGN KEY 
    ( 
     Dim_Movie_SK_Movie
    ) 
    REFERENCES Dim_Movie 
    ( 
     SK_Movie 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Platform_FK FOREIGN KEY 
    ( 
     Dim_Platform_SK_Platform
    ) 
    REFERENCES Dim_Platform 
    ( 
     SK_Platform 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
